=== littlebyteorg/appledb/schemas/bypassApps.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Apps with jailbreak detection",
    "description": "Description of an app with jailbreak detection",

    "type": "object",
    "additionalProperties": false,
    "properties": {
        "name": {"type": "string"},
        "bundleId": {"type": "string"},
        "uri": {"type": "string", "format": "uri"},
        "icon": {"type": "string", "format": "uri"},
        "notes": {"type": "string"},
        "aliases": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {"type": "string"}
        },
        "bypasses": {
            "anyOf": [
                {"type": "null"},
                {
                    "type": "array",
                    "uniqueItems": true,
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "name": {"type": "string"},
                            "notes": {"type": "string"},
                            "version": {"type": "string"}
                        }
                    }
                }
            ]
        }
    }
}

=== littlebyteorg/appledb/bypassApps/com.netflix.Netflix.json
{
    "name": "Netflix",
    "bundleId": "com.netflix.Netflix",
    "uri": "https://apps.apple.com/us/app/netflix/id363590051",
    "icon": "https://is2-ssl.mzstatic.com/image/thumb/Purple116/v4/95/7a/b2/957ab2bb-2080-fccc-e494-b5ef28572cf2/source/512x512bb.jpg",
    "bypasses": [
        {
            "name": "Choicy"
        },
        {
            "name": "libhooker-configurator"
        },
        {
            "notes": "Looks like jailbreak detection has been removed from the app; however, raise an issue on GitHub if you find any trouble."
        }
    ]
}

=== littlebyteorg/appledb/bypassApps/com.db.pbc.ng.mobile.json
{
    "name": "Deutsche Bank Mobile",
    "bundleId": "com.db.pbc.ng.mobile",
    "uri": "https://apps.apple.com/us/app/deutsche-bank-mobile/id1040475847",
    "icon": "https://is2-ssl.mzstatic.com/image/thumb/Purple126/v4/b9/43/38/b9433800-3c28-9264-6bad-bf7bff26e623/source/512x512bb.jpg",
    "bypasses": [
        {
            "name": "A-Bypass"
        },
        {
            "name": "Shadow"
        }
    ]
}
