=== littlebyteorg/appledb/schemas/deviceFiles.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Apple Device",
    "description": "Description of an Apple device",

    "type": "object",
    "additionalProperties": false,
    "properties": {
        "name":           {"type": "string"},
        "identifier":     {
            "anyOf": [
                {"type": "string"},
                {"type": "array", "items": {"type": "string"}}
            ]
        },
        "alias":          {"type": "array", "items": {"type": "string"}},
        "key":            {"type": "string"},
        "imageKey":            {"type": "string"},
        "appLink":        {
            "anyOf": [
                {"type": "array", "items": {"$ref": "#/definitions/appLink"}},
                {"$ref": "#/definitions/appLink"}
            ]
        },
        "soc": {
            "anyOf": [
                {"type": "string"},
                {"type": "array", "items": {"type": "string"}}
            ]
        },
        "cpid": {
            "anyOf": [
                {"$ref": "#/definitions/hex"},
                {"type": "array", "items": {"$ref": "#/definitions/hex"}}
            ]
        },
        "arch":           {"type": "string"},
        "type":           {"type": "string"},
        "board": {
            "anyOf": [
                {"type": "string"},
                {"type": "array", "items": {"type": "string"}}
            ]
        },
        "bdid":           {"$ref": "#/definitions/hex"},
        "iBridge":        {"type": "string"},
        "model": {
            "anyOf": [
                {"type": "string"},
                {"type": "array", "items": {"type": "string"}}
            ]
        },
        "internal":       {"type": "boolean"},
        "group":          {"type": "boolean"},
        "released": {
            "anyOf": [
                {"$ref": "#/definitions/partial-date"},
                {"type": "array", "items": {"$ref": "#/definitions/partial-date"}}
            ]
        },
        "discontinued":   {
            "anyOf": [
                {"$ref": "#/definitions/partial-date"},
                {"type": "array", "items": {"$ref": "#/definitions/partial-date"}}
            ]
        },
        "info":           {"type": "array", "items": {"type": "object"}},
        "colors":         {"type": "array", "items": {"$ref": "#/definitions/color"}},
        "windowsStoreId": {"type": "string"},
        "extra":          {"type": "object"}
    },
    "definitions": {
        "hex": {
            "type": "string",
            "pattern": "^0x[0-9a-fA-F]+$"
        },
        "color-hex": {
            "type": "string",
            "pattern": "^[0-9a-fA-F]{6}$"
        },
        "partial-date": {
            "anyOf": [
                {"type": "string", "format": "date-time"},
                {"type": "string", "format": "date"},
                {"type": "string", "pattern": "^\\d{4}-\\d{2}$"},
                {"type": "string", "pattern": "^\\d{4}$"},
                {"type": "string", "maxLength": 0}
            ]
        },
        "color": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {"type": "string"},
                "key": {"type": "string"},
                "group": {"type": "string"},
                "hex": {
                    "anyOf": [
                        {"$ref": "#/definitions/color-hex"},
                        {"type": "array", "items": {"$ref": "#/definitions/color-hex"}}
                    ]
                },
                "released": {"$ref": "#/definitions/partial-date"},
                "discontinued": {"$ref": "#/definitions/partial-date"},
                "configurations": {"$ref": "#/definitions/configurations"}
            },
            "required": ["name", "hex"]
        },
        "storage-unit": {
                    "type": "string",
                    "enum": ["MB", "GB", "TB"]
                },
        "configurations": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "storage": {
                        "type": "object",
                        "properties": {
                            "capacity": {"type": "integer"},
                            "unit": {"$ref": "#/definitions/storage-unit"},
                            "type": {
                                "type": "string",
                                "enum": ["HDD", "Fusion", "SSD"]
                            }
                        },
                        "required": ["capacity", "unit", "type"]
                    },
                    "memory": {
                        "type": "object",
                        "properties": {
                            "capacity": {"type": "number"},
                            "unit": {"$ref": "#/definitions/storage-unit"}
                        },
                        "required": ["capacity", "unit"]
                    },
                    "released": {"$ref": "#/definitions/partial-date"},
                    "discontinued": {"$ref": "#/definitions/partial-date"}
                },
                "additionalProperties": false,
                "required": ["storage", "memory"]
            },
            "minimum": 1
        },
        "sourceLink": {
            "type": "object",
            "additionalProperties": false,
            "required": ["url", "active"],
            "properties": {
                "url": {"type": "string", "format": "uri"},
                "label": {"type": "string"},
                "active": {"type": "boolean"}
            }
        },
        "appLink": {
            "anyOf": [
                {"type": "string", "format": "uri"},
                {"$ref": "#/definitions/sourceLink"}
            ]
        }
    }
}

=== littlebyteorg/appledb/deviceFiles/iPad/iPad4,9.json
{
    "name": "iPad mini 3 Wi-Fi + Cellular (TD-LTE)",
    "identifier": "iPad4,9",
    "imageKey": "iPad4,7",
    "soc": "A7",
    "cpid": "0x8960",
    "arch": "arm64",
    "type": "iPad mini",
    "board": "J87mAP",
    "bdid": "0x36",
    "model": "A1601",
    "released": "2014-12-11",
    "discontinued": "2015-09-09",
    "colors": [
        {
            "name": "Gold",
            "hex": "D2BBA9",
            "released": "2014-12-11",
            "discontinued": "2015-09-09",
            "configurations": [
                {
                    "storage": {
                        "capacity": 16,
                        "unit": "GB",
                        "type": "SSD"
                    },
                    "memory": {
                        "capacity": 1,
                        "unit": "GB"
                    },
                    "released": "2014-12-11",
                    "discontinued": "2015-09-09"
                },
                {
                    "storage": {
                        "capacity": 64,
                        "unit": "GB",
                        "type": "SSD"
                    },
                    "memory": {
                        "capacity": 1,
                        "unit": "GB"
                    },
                    "released": "2014-12-11",
                    "discontinued": "2015-09-09"
                },
                {
                    "storage": {
                        "capacity": 128,
                        "unit": "GB",
                        "type": "SSD"
                    },
                    "memory": {
                        "capacity": 1,
                        "unit": "GB"
                    },
                    "released": "2014-12-11",
                    "discontinued": "2015-09-09"
                }
            ]
        },
        {
            "name": "Silver",
            "hex": "D5D7D8",
            "released": "2014-12-11",
            "discontinued": "2015-09-09",
            "configurations": [
                {
                    "storage": {
                        "capacity": 16,
                        "unit": "GB",
                        "type": "SSD"
                    },
                    "memory": {
                        "capacity": 1,
                        "unit": "GB"
                    },
                    "released": "2014-12-11",
                    "discontinued": "2015-09-09"
                },
                {
                    "storage": {
                        "capacity": 64,
                        "unit": "GB",
                        "type": "SSD"
                    },
                    "memory": {
                        "capacity": 1,
                        "unit": "GB"
                    },
                    "released": "2014-12-11",
                    "discontinued": "2015-09-09"
                },
                {
                    "storage": {
                        "capacity": 128,
                        "unit": "GB",
                        "type": "SSD"
                    },
                    "memory": {
                        "capacity": 1,
                        "unit": "GB"
                    },
                    "released": "2014-12-11",
                    "discontinued": "2015-09-09"
                }
            ]
        },
        {
            "name": "Space Gray",
            "hex": "A4A5AB",
            "released": "2014-12-11",
            "discontinued": "2015-09-09",
            "configurations": [
                {
                    "storage": {
                        "capacity": 16,
                        "unit": "GB",
                        "type": "SSD"
                    },
                    "memory": {
                        "capacity": 1,
                        "unit": "GB"
                    },
                    "released": "2014-12-11",
                    "discontinued": "2015-09-09"
                },
                {
                    "storage": {
                        "capacity": 64,
                        "unit": "GB",
                        "type": "SSD"
                    },
                    "memory": {
                        "capacity": 1,
                        "unit": "GB"
                    },
                    "released": "2014-12-11",
                    "discontinued": "2015-09-09"
                },
                {
                    "storage": {
                        "capacity": 128,
                        "unit": "GB",
                        "type": "SSD"
                    },
                    "memory": {
                        "capacity": 1,
                        "unit": "GB"
                    },
                    "released": "2014-12-11",
                    "discontinued": "2015-09-09"
                }
            ]
        }
    ]
}

=== littlebyteorg/appledb/device/iPhone14,3.json
{"name":"iPhone 13 Pro Max","identifier":["iPhone14,3"],"soc":"A15","cpid":"0x8110","arch":"arm64e","type":"iPhone","board":["D64AP"],"bdid":"0x0E","model":["A2484","A2641","A2643","A2644","A2645"],"released":["2021-09-24","2022-03-18"],"discontinued":"2022-09-07","colors":[{"name":"Alpine Green","hex":"546554","released":"2022-03-18","discontinued":"2022-09-07","key":"Alpine Green"},{"name":"Gold","hex":"F6E4C7","released":"2021-09-24","discontinued":"2022-09-07","key":"Gold"},{"name":"Graphite","hex":"4C4C4A","released":"2021-09-24","discontinued":"2022-09-07","key":"Graphite"},{"name":"Sierra Blue","hex":"93A9C0","released":"2021-09-24","discontinued":"2022-09-07","key":"Sierra Blue"},{"name":"Silver","hex":"F1F1E7","released":"2021-09-24","discontinued":"2022-09-07","key":"Silver"}],"info":[{"type":"SoC","SoC":"A15","Architecture":"arm64e (64-bit)","Manufacturing_Process":"5nm"},{"type":"Cores","CPU_Core_Count":6,"Performance_Cores":"2 @ 3.23 GHz","Efficiency_Cores":"4 @ 1.82 GHz","GPU_Core_Count":5,"Neural_Engine_Core_Count":16},{"type":"Memory","Storage":["128GB","256GB","512GB","1TB"],"RAM":"6GB LPDDR4X"},{"type":"Power","Battery_Capacity":"4,352mAh","Battery_Life":"28 hours","Charger":"20W Lightning"},{"type":"Connectivity","Ports":"1x Lightning","Cellular":["5G (sub-6 GHz and mmWave) with 4x4 MIMO","Gigabit LTE with 4x4 MIMO and LAA"],"Wi-Fi":"Wi‑Fi 6 (802.11ax) with 2x2 MIMO","Bluetooth":"5.0","Ultra-wideband":true},{"type":"Sensors","Front_Camera":["12MP sensor","ƒ/2.2 aperture"],"Telephoto_Camera":["12MP sensor","ƒ/2.8 aperture","3x optical zoom in","Optical image stabilization"],"Wide_Camera":["12MP sensor","ƒ/1.5 aperture","Optical image stabilization"],"Ultrawide_Camera":["12MP sensor","ƒ/1.8 aperture","120° field of view","2x optical zoom out","Optical image stabilization"],"TrueDepth_Camera":["12MP LiDAR sensor","ƒ/2.2 aperture"],"Biometrics":"Face ID sensor","Other":["Ambient Light Sensor","Accelerometer","Proximity sensor","Gyroscope","Compass","Barometer"]},{"type":"Audio","Channels":"Stereo","Headphone_Jack":false,"Microphone":true},{"type":"Display","Resolution":{"x":2778,"y":1284},"Screen_Size":"6.7\"","Refresh_Rate":"120 Hz","Peak_Brightness":["1000 nits","1200 nits (HDR)"],"Color_Gamut":"P3","True_Tone":true,"ProMotion":true,"Pixels_per_Inch":510}],"key":"iPhone14,3","imageKey":"iPhone14,3"}

=== littlebyteorg/appledb/device/AppleTV1,1.json
{"name":"Apple TV (1st generation)","identifier":["AppleTV1,1"],"soc":"Pentium M","arch":"x86","type":"Apple TV","board":["Mac-F4228DC8"],"model":["A1218"],"released":["2007-03-21","2007-05-31"],"discontinued":["2009-09-14","2010-09-01"],"colors":[{"name":"Silver","hex":"D9DDE0","released":"2007-03-21","discontinued":"2010-09-01","key":"Silver"}],"key":"AppleTV1,1","imageKey":"AppleTV1,1"}

=== littlebyteorg/appledb/device/Watch7,14.json
{"name":"Apple Watch SE 3 (GPS, 44mm)","identifier":["Watch7,14"],"soc":"S10","cpid":"0x8310","arch":"arm64","type":"Apple Watch","board":["N243bAP"],"bdid":"0x2A","model":["A3325","A3392"],"released":"2025-09-19","colors":[{"name":"Midnight","hex":"161B21","released":"2025-09-19","key":"Midnight"},{"name":"Starlight","hex":"A1948C","released":"2025-09-19","key":"Starlight"}],"key":"Watch7,14","imageKey":"Watch7,14"}

=== littlebyteorg/appledb/device/iMac14,3.json
{"name":"iMac (21.5-inch, Late 2013, Dedicated Graphics)","identifier":["iMac14,3"],"imageKey":"iMac14,1","arch":"x86-64","type":"iMac","board":["Mac-77EB7D7DAF985301"],"model":["A1418"],"released":"2013-09-24","discontinued":"2015-10-13","colors":[{"name":"Silver","hex":"E9E9EB","released":"2013-09-24","discontinued":"2015-10-13","key":"Silver"}],"key":"iMac14,3"}
