=== littlebyteorg/appledb/schemas/osFiles.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Apple OS",
    "description": "Description of an Apple operating system release",
    "$ref": "#/definitions/os",
    "type": "object",
    "required": ["osStr", "version"],
    "definitions": {
        "os": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "osStr":         {"type": "string"},
                "version":       {"type": "string", "not": { "pattern": "FIXME" }},
                "iosVersion":    {"type": "string"},
                "safariVersion": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "build":         {"type": "string"},
                "restoreVersion": {"type": "string"},
                "buildId":       {"type": "string", "format": "uuid"},
                "uniqueBuild":   {"type": "string"},
                "key":           {"type": "string"},
                
                "bridgeOSBuild":    {"type": "string"},
                "embeddedOSBuild":  {"type": "string"},
                "basebandVersions": {
                    "type":"object",
                    "additionalProperties": true
                },
                "buildTrain":    {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },

                "released":     {"anyOf": [
                    {"type": "string", "format": "date-time"},
                    {"type": "string", "format": "date"},
                    {"type": "string", "pattern": "^\\d{4}-\\d{2}$"},
                    {"type": "string", "pattern": "^\\d{4}$"},
                    {"type": "string", "maxLength": 0}
                ]},
                "rc":           {"type": "boolean"},
                "beta":         {"type": "boolean"},
                "rsr":          {"type": "boolean"},
                "internal":     {"type": "boolean"},
                "hideFromLatestVersions": {"type": "boolean"},
                "notes":        {"type": "string"},
                "releaseNotes": {
                    "anyOf": [
                        {"type": "string", "format": "uri"},
                        {"$ref": "#/definitions/sourceLink"}
                    ]
                },
                "securityNotes": {
                    "anyOf": [
                        {"type": "string", "format": "uri"},
                        {"$ref": "#/definitions/sourceLink"}
                    ]
                },

                "preinstalled": {
                    "anyOf": [
                        {"type": "boolean"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "deviceMap": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "uniqueItems": true
                },
                "osMap": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "uniqueItems": true
                },
                "ipd": {
                    "type": "object",
                    "properties": {
                        "AudioAccessory": {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "AppleTV":  {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPhone":   {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPad":     {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPod":     {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        }
                    },
                    "additionalProperties": {
                        "anyOf": [
                            {"type": "string", "format": "uri"},
                            {"$ref": "#/definitions/sourceLink"}
                        ]
                    }
                },
                "createDuplicateEntries": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "allOf": [
                            {"$ref": "#/definitions/os"},
                            {"type": "object", "properties": {"createDuplicateEntries": false}}
                        ]
                    }
                },
                "sdks": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "beta": {"type": "boolean"},
                            "build": {"type": "string"},
                            "osStr": {"type": "string"},
                            "rc": {"type": "boolean"},
                            "version": {"type": "string"}
                        }
                    }
                },
                "appledbWebImage": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "id": {"type": "string"},
                        "align": {"type": "string"}
                    }
                },
                "appledbUrl": {"type": "string"},
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["type", "links", "deviceMap"],
                        "properties": {
                            "type": {"enum": ["ipsw", "ota", "update", "kdk", "installassistant", "combo", "pkg", "aar", "dmg", "exe", "appx", "apk", "xip", "tar", "bin", "ipa", "xpi"]},
                            "deviceMap": {"$ref": "#/definitions/os/properties/deviceMap"},
                            "boardMap": {
                                "type": "array",
                                "minItems": 1,
                                "items": {"type": "string"},
                                "uniqueItems": true
                            },
                            "osMap": {"$ref": "#/definitions/os/properties/osMap"},
                            "skipUpdateLinks": {"type": "boolean"},
                            "windowsUpdateDetails": {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "updateId": {"type": "string", "format": "uuid"},
                                    "revisionId": {"type": "string", "pattern": "^\\w+$"}
                                }
                            },
                            "hashes": {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "md5":      { "type": "string", "pattern": "^[0-9a-f]{32}$" },
                                    "sha1":     { "type": "string", "pattern": "^[0-9a-f]{40}$" },
                                    "sha2-256": { "type": "string", "pattern": "^[0-9a-f]{64}$" },
                                    "sha2-512": { "type": "string", "pattern": "^[0-9a-f]{128}$" }
                                }
                            },
                            "links": {
                                "type": "array",
                                "minItems": 1,
                                "items": {
                                    "$ref": "#/definitions/sourceLink"
                                }
                            },
                            "prerequisiteBuild": {
                                "anyOf": [
                                    {"type": "string"},
                                    {"type": "array", "minItems": 1, "items": {"type": "string"}}
                                ]
                            },
                            "systemImageId": {"type": "string", "format": "uuid"},
                            "size": {"type": "integer"}
                        }
                    }
                }
            }
        },
        "sourceLink": {
            "type": "object",
            "additionalProperties": false,
            "required": ["url", "active"],
            "properties": {
                "url": {"type": "string", "format": "uri"},
                "decryptionKey": {"type": "string"},
                "active": {"type": "boolean"},
                "catalog": {"enum": ["dev-beta", "public-beta"]}
            }
        }
    }
}

=== littlebyteorg/appledb/osFiles/bridgeOS/22x - 9.x/22P53034a.json
{
    "osStr": "bridgeOS",
    "version": "9.3 beta",
    "build": "22P53034a",
    "restoreVersion": "22.16.13034.5.1,0",
    "buildId": "7C46A290-B464-11EF-A4E5-165E38E3F4F5",
    "buildTrain": "GlowBridgeDSeed",
    "released": "2024-12-16",
    "beta": true,
    "deviceMap": [
        "iBridge2,1",
        "iBridge2,3",
        "iBridge2,4",
        "iBridge2,5",
        "iBridge2,6",
        "iBridge2,7",
        "iBridge2,8",
        "iBridge2,10",
        "iBridge2,12",
        "iBridge2,14",
        "iBridge2,15",
        "iBridge2,16",
        "iBridge2,19",
        "iBridge2,20",
        "iBridge2,21",
        "iBridge2,22"
    ],
    "sources": [
        {
            "type": "pkg",
            "systemImageId": "6430A12B-699E-4115-8E24-A7A28552B5E3",
            "deviceMap": [
                "iBridge2,1",
                "iBridge2,3",
                "iBridge2,4",
                "iBridge2,5",
                "iBridge2,6",
                "iBridge2,7",
                "iBridge2,8",
                "iBridge2,10",
                "iBridge2,12",
                "iBridge2,14",
                "iBridge2,15",
                "iBridge2,16",
                "iBridge2,19",
                "iBridge2,20",
                "iBridge2,21",
                "iBridge2,22"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/54/52/072-29309-A_5ZVGY42H2T/5intrdqgatjfygu8a3l2uly3r1jdrxze8d/BridgeOSUpdateCustomer.pkg",
                    "catalog": "dev-beta",
                    "active": false
                },
                {
                    "url": "https://swcdn.apple.com/content/downloads/08/55/072-29309-A_D2NBM63N7J/1ibakdgorjgyfn07nzc12h4auncp8l4tso/BridgeOSUpdateCustomer.pkg",
                    "catalog": "public-beta",
                    "active": false
                }
            ],
            "hashes": {
                "sha1": "416425a67a97b48fd0dffb3606d3e488cee379c7"
            },
            "size": 542144093
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Rosetta/25x - 26.x/25A362.json
{
    "osStr": "Rosetta",
    "version": "26.0.1",
    "build": "25A362",
    "released": "2025-09-29",
    "deviceMap": [
        "Rosetta"
    ],
    "sources": [
        {
            "type": "pkg",
            "deviceMap": [
                "Rosetta"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/22/02/093-50752-A_0XW0LFBB4A/ohe8i7nkwiuri631vj904un8ycglxrh7z7/RosettaUpdateAuto.pkg",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "89bef6aef110e67d3a0f0fadb15bbeb2f9ba70de"
            },
            "size": 496541
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Safari Technology Preview/125.json
{
    "osStr": "Safari Technology Preview",
    "version": "125",
    "safariVersion": "14.2",
    "released": "2021-05-26",
    "beta": true,
    "releaseNotes": "https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-125",
    "deviceMap": [
        "Safari Technology Preview"
    ],
    "osMap": [
        "macOS 10.15",
        "macOS 11"
    ],
    "sources": [
        {
            "type": "dmg",
            "deviceMap": [
                "Safari Technology Preview"
            ],
            "osMap": [
                "macOS 10.15"
            ],
            "links": [
                {
                    "url": "https://secure-appldnld.apple.com/STP/071-44527-20210526-93430244-0334-4fae-878d-56502a656003/SafariTechnologyPreview.dmg",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "7412911c5261d7c810b0826d475060d3",
                "sha1": "7676bd5301b3de808b3e92728c28de9cadf0ada2",
                "sha2-256": "6ea830ec5c9101665e18d77f31a7f220a0fc8afc35b9ac036ee29d5ee3dbdd23"
            },
            "size": 77276603
        },
        {
            "type": "dmg",
            "deviceMap": [
                "Safari Technology Preview"
            ],
            "osMap": [
                "macOS 11"
            ],
            "links": [
                {
                    "url": "https://secure-appldnld.apple.com/STP/071-45899-20210526-3fe7359c-0f20-4850-b6ec-da9b197119c2/SafariTechnologyPreview.dmg",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "49490e3084c532282b6c512e8540df96",
                "sha1": "23e38f41a5b14a9438a4ee6cf2c0c2756c8653d0",
                "sha2-256": "63e4961fd0cca345b58128c0edb33627847d02b99a77613c54c0a89e6402d36e"
            },
            "size": 103340942
        },
        {
            "type": "pkg",
            "deviceMap": [
                "Safari Technology Preview"
            ],
            "osMap": [
                "macOS 10.15"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/10/15/071-44528-A_BN6JLWWLQA/eeud2jei50gdvrpeo6zijd8rfy918euhl8/SafariTechPreview.pkg",
                    "active": false
                }
            ],
            "size": 77223273
        },
        {
            "type": "pkg",
            "deviceMap": [
                "Safari Technology Preview"
            ],
            "osMap": [
                "macOS 11"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/20/34/071-45900-A_AJCV7RQXCB/ul2gaalwp4z3054rya1jqd80g3hh0h6ogi/SafariTechPreview.pkg",
                    "active": false
                }
            ],
            "size": 103286139
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Safari Technology Preview/131.json
{
    "osStr": "Safari Technology Preview",
    "version": "131",
    "safariVersion": "15.0",
    "released": "2021-09-01",
    "beta": true,
    "releaseNotes": "https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-131",
    "deviceMap": [
        "Safari Technology Preview"
    ],
    "osMap": [
        "macOS 11",
        "macOS 12"
    ],
    "sources": [
        {
            "type": "dmg",
            "deviceMap": [
                "Safari Technology Preview"
            ],
            "osMap": [
                "macOS 11"
            ],
            "links": [
                {
                    "url": "https://secure-appldnld.apple.com/STP/071-89240-20210831-f3c13847-02d7-4370-8f35-d1342dd5d063/SafariTechnologyPreview.dmg",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "95830c85eccfb864fec21981da14474b",
                "sha1": "301292e9c4708d6d26ceee55fb1b84071ce69acc",
                "sha2-256": "c354190f1d54106b1e74432108a14b811aeb830a688cf1050fbf2968ee59d862"
            },
            "size": 109837550
        },
        {
            "type": "dmg",
            "deviceMap": [
                "Safari Technology Preview"
            ],
            "osMap": [
                "macOS 12"
            ],
            "links": [
                {
                    "url": "https://secure-appldnld.apple.com/STP/071-89239-20210831-1d619787-79dc-4b2d-8ce5-5ebd5c210b54/SafariTechnologyPreview.dmg",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "9832f464c58721e45ca38db3a951a980",
                "sha1": "2795bc7d29e20ee3ad5ac42e6c39bb2afcfeff4f",
                "sha2-256": "50e28d3f49e6c797d7870c812165e3829db1a887d1c670dc8aab8a338464c56c"
            },
            "size": 110988592
        },
        {
            "type": "pkg",
            "deviceMap": [
                "Safari Technology Preview"
            ],
            "osMap": [
                "macOS 11"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/11/22/071-89241-A_S1JOYCQNLK/u2vbzm02agnuzsfu9farh38e1kjmh6kcuy/SafariTechPreview.pkg",
                    "active": false
                }
            ],
            "size": 109782915
        },
        {
            "type": "pkg",
            "deviceMap": [
                "Safari Technology Preview"
            ],
            "osMap": [
                "macOS 12"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/04/14/071-89238-A_ZHBT7TZ971/0ycm1iquvg2nvfxkh469chk3yuboabac5c/SafariTechPreview.pkg",
                    "active": false
                }
            ],
            "size": 110933932
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Safari/16.x/614A94.json
{
    "osStr": "Safari",
    "version": "16.1",
    "build": "614A94",
    "released": "2022-10-24",
    "releaseNotes": {
        "url": "https://developer.apple.com/documentation/safari-release-notes/safari-16_1-release-notes",
        "active": true
    },
    "securityNotes": {
        "url": "https://support.apple.com/HT213495",
        "active": true
    },
    "deviceMap": [
        "Safari (macOS)"
    ],
    "osMap": [
        "macOS 11"
    ],
    "sources": [
        {
            "type": "pkg",
            "deviceMap": [
                "Safari (macOS)"
            ],
            "osMap": [
                "macOS 11"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/06/51/012-26885-A_XE7OL6TYXT/3di69zxamb1frajv1zf4dnei1jaz0765vn/Safari16.1BigSurAuto.pkg",
                    "active": false
                }
            ],
            "size": 128299069
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Rosetta/22x - 13.x/22G436.json
{
    "osStr": "Rosetta",
    "version": "13.6.3",
    "build": "22G436",
    "released": "2023-12-05",
    "deviceMap": [
        "Rosetta"
    ],
    "sources": [
        {
            "type": "pkg",
            "deviceMap": [
                "Rosetta"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/38/33/052-14625-A_ZJWKS3ZAYE/5jmpjy9quv3jtgqh2q2kzjk2hk9csm7qyq/RosettaUpdateAuto.pkg",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "61a1455ede9b27f9c1c3042eaf0b7559c1a2d949"
            },
            "size": 334172
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Bluetooth Headset Firmware/7x/7E101.json
{
    "osStr": "Bluetooth Headset Firmware",
    "version": "7.4",
    "build": "7E101",
    "buildTrain": "DiscoE",
    "released": "2025-04-02",
    "releaseNotes": "https://support.apple.com/106340",
    "deviceMap": [
        "AirPodsMax1,1-usbc"
    ],
    "sources": [
        {
            "type": "ota",
            "deviceMap": [
                "AirPodsMax1,1-usbc"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2025/patches/082-23134/89EBD8F5-A61D-46F4-AE8E-BF5639C30DD1/com_apple_MobileAsset_MobileAccessoryUpdate_A3184_EA/76d2ac7d72d48706f5adc296908c12348b2c2c74.zip",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "474239f08556c3fe405085f32b19b023",
                "sha1": "db2f7bd31c40bb0ea04673051db5a915f0177b14",
                "sha2-256": "b53b2804b3085a91c3d9200ed31392bd45f282f25bbea065ad03d77d5f419913"
            },
            "size": 3226960
        }
    ]
}
