=== littlebyteorg/appledb/schemas/osFiles.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Apple OS",
    "description": "Description of an Apple operating system release",
    "$ref": "#/definitions/os",
    "type": "object",
    "required": ["osStr", "version"],
    "definitions": {
        "os": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "osStr":         {"type": "string"},
                "version":       {"type": "string", "not": { "pattern": "FIXME" }},
                "iosVersion":    {"type": "string"},
                "safariVersion": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "build":         {"type": "string"},
                "restoreVersion": {"type": "string"},
                "buildId":       {"type": "string", "format": "uuid"},
                "uniqueBuild":   {"type": "string"},
                "key":           {"type": "string"},
                
                "bridgeOSBuild":    {"type": "string"},
                "embeddedOSBuild":  {"type": "string"},
                "basebandVersions": {
                    "type":"object",
                    "additionalProperties": true
                },
                "buildTrain":    {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },

                "released":     {"anyOf": [
                    {"type": "string", "format": "date-time"},
                    {"type": "string", "format": "date"},
                    {"type": "string", "pattern": "^\\d{4}-\\d{2}$"},
                    {"type": "string", "pattern": "^\\d{4}$"},
                    {"type": "string", "maxLength": 0}
                ]},
                "rc":           {"type": "boolean"},
                "beta":         {"type": "boolean"},
                "rsr":          {"type": "boolean"},
                "internal":     {"type": "boolean"},
                "hideFromLatestVersions": {"type": "boolean"},
                "notes":        {"type": "string"},
                "releaseNotes": {
                    "anyOf": [
                        {"type": "string", "format": "uri"},
                        {"$ref": "#/definitions/sourceLink"}
                    ]
                },
                "securityNotes": {
                    "anyOf": [
                        {"type": "string", "format": "uri"},
                        {"$ref": "#/definitions/sourceLink"}
                    ]
                },

                "preinstalled": {
                    "anyOf": [
                        {"type": "boolean"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "deviceMap": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "uniqueItems": true
                },
                "osMap": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "uniqueItems": true
                },
                "ipd": {
                    "type": "object",
                    "properties": {
                        "AudioAccessory": {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "AppleTV":  {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPhone":   {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPad":     {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPod":     {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        }
                    },
                    "additionalProperties": {
                        "anyOf": [
                            {"type": "string", "format": "uri"},
                            {"$ref": "#/definitions/sourceLink"}
                        ]
                    }
                },
                "createDuplicateEntries": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "allOf": [
                            {"$ref": "#/definitions/os"},
                            {"type": "object", "properties": {"createDuplicateEntries": false}}
                        ]
                    }
                },
                "sdks": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "beta": {"type": "boolean"},
                            "build": {"type": "string"},
                            "osStr": {"type": "string"},
                            "rc": {"type": "boolean"},
                            "version": {"type": "string"}
                        }
                    }
                },
                "appledbWebImage": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "id": {"type": "string"},
                        "align": {"type": "string"}
                    }
                },
                "appledbUrl": {"type": "string"},
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["type", "links", "deviceMap"],
                        "properties": {
                            "type": {"enum": ["ipsw", "ota", "update", "kdk", "installassistant", "combo", "pkg", "aar", "dmg", "exe", "appx", "apk", "xip", "tar", "bin", "ipa", "xpi"]},
                            "deviceMap": {"$ref": "#/definitions/os/properties/deviceMap"},
                            "boardMap": {
                                "type": "array",
                                "minItems": 1,
                                "items": {"type": "string"},
                                "uniqueItems": true
                            },
                            "osMap": {"$ref": "#/definitions/os/properties/osMap"},
                            "skipUpdateLinks": {"type": "boolean"},
                            "windowsUpdateDetails": {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "updateId": {"type": "string", "format": "uuid"},
                                    "revisionId": {"type": "string", "pattern": "^\\w+$"}
                                }
                            },
                            "hashes": {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "md5":      { "type": "string", "pattern": "^[0-9a-f]{32}$" },
                                    "sha1":     { "type": "string", "pattern": "^[0-9a-f]{40}$" },
                                    "sha2-256": { "type": "string", "pattern": "^[0-9a-f]{64}$" },
                                    "sha2-512": { "type": "string", "pattern": "^[0-9a-f]{128}$" }
                                }
                            },
                            "links": {
                                "type": "array",
                                "minItems": 1,
                                "items": {
                                    "$ref": "#/definitions/sourceLink"
                                }
                            },
                            "prerequisiteBuild": {
                                "anyOf": [
                                    {"type": "string"},
                                    {"type": "array", "minItems": 1, "items": {"type": "string"}}
                                ]
                            },
                            "systemImageId": {"type": "string", "format": "uuid"},
                            "size": {"type": "integer"}
                        }
                    }
                }
            }
        },
        "sourceLink": {
            "type": "object",
            "additionalProperties": false,
            "required": ["url", "active"],
            "properties": {
                "url": {"type": "string", "format": "uri"},
                "decryptionKey": {"type": "string"},
                "active": {"type": "boolean"},
                "catalog": {"enum": ["dev-beta", "public-beta"]}
            }
        }
    }
}

=== littlebyteorg/appledb/osFiles/visionOS/22x - 2.x/22N5277g.json
{
    "osStr": "visionOS",
    "version": "2.0 beta 3",
    "build": "22N5277g",
    "restoreVersion": "22.14.277.5.7,0",
    "buildId": "3DE3F8E8-3A77-11EF-9541-E9195F52984A",
    "buildTrain": "ConstellationSeed",
    "released": "2024-07-08",
    "beta": true,
    "appledbWebImage": {
        "id": "visionos2",
        "align": "left"
    },
    "deviceMap": [
        "RealityDevice14,1"
    ],
    "sources": [
        {
            "type": "ipsw",
            "deviceMap": [
                "RealityDevice14,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2024SummerSeed/fullrestores/062-23675/5ABEAC80-17C5-4D12-9932-A39D70719A38/Apple_Vision_Pro_2.0_22N5277g_Restore.ipsw",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "30a93b58850d3b41166ef9604fc132b209bc0354",
                "sha2-256": "4268722827148da22e637aaaa8d8a18315589a37d955244e7f04669d289605fe"
            },
            "size": 10168770244
        },
        {
            "type": "ota",
            "systemImageId": "80A98480-61DD-4EDF-98DC-1AD9E098540D",
            "deviceMap": [
                "RealityDevice14,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2024SummerSeed/mobileassets/062-23674/17DCF925-2B95-4AAF-8EFD-D1E2C02A782E/com_apple_MobileAsset_SoftwareUpdate/a32a88ad0a96281c9fbf5e645b2c0345f60d01cfcebf06cdd703dc0a72dc7bbf.aea",
                    "decryptionKey": "Wp+qowafmYWVwmmT1tfaoodZmLNXa3pAaXgrmSemQcY=",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "d5419e2bf83f940749906b83afd2f4f708fdeb29",
                "sha2-256": "c345f103626ca466266cd2827e40a4288827de84bca07d46bfe58819c8272fdc"
            },
            "size": 8321499136
        },
        {
            "type": "ota",
            "prerequisiteBuild": "21O5761a",
            "deviceMap": [
                "RealityDevice14,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2024SummerSeed/mobileassets/062-32225/B4EDA1C9-74C9-4098-B6F5-F5A624E190C0/com_apple_MobileAsset_SoftwareUpdate/acc92293f642a8a9c40276d0cb9338621ef27068ff77a8f5d48a7e25bfa5e79d.aea",
                    "decryptionKey": "Wa9FNYdY6GPfbXVyd8o9IJRalthDlX9WR1dtQddUSVY=",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "a9d574b2c052aa6072f20488d463c62c53aea0ba",
                "sha2-256": "69103455857f57d91e4420924d378c2a343fbf7983262d2f2ccdf64c683d6d49"
            },
            "size": 3623878656
        },
        {
            "type": "ota",
            "prerequisiteBuild": "22N5267g",
            "deviceMap": [
                "RealityDevice14,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2024SummerSeed/mobileassets/062-23672/0DF3617F-E470-4E25-924D-D1BFB8551D69/com_apple_MobileAsset_SoftwareUpdate/93490e4647ae99821c6e5fc3ed99ab2ccefbb7e19a1b3fbbf14bc905dacf5a4a.aea",
                    "decryptionKey": "kggXr4tJGFCvHAZgBmDhtgf5N+RdXzc7NT/QvdeHh5w=",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "ed136af968bf6abc4f551f98cd26821cba5ceb44",
                "sha2-256": "45e53651a8a57f115e51e9d87e6cc459868d31a92e562d3d849d51028321ab4d"
            },
            "size": 989855744
        }
    ]
}

=== littlebyteorg/appledb/osFiles/macOS/12x - 10.8.x/12E1009.json
{
    "osStr": "OS X",
    "version": "10.8.4 (Security Update 2013-003)",
    "build": "12E1009",
    "released": "2013-07-02",
    "releaseNotes": {
        "url": "https://support.apple.com/kb/DL1667",
        "active": false
    },
    "securityNotes": "https://support.apple.com/HT201366",
    "appledbWebImage": {
        "id": "Mountain Lion",
        "align": "left"
    },
    "deviceMap": [
        "iMac7,1-20-inch",
        "iMac7,1-24-inch",
        "iMac8,1-20-inch",
        "iMac8,1-24-inch",
        "iMac9,1-20-inch-Early-2009",
        "iMac9,1-20-inch-Mid-2009",
        "iMac9,1-24-inch",
        "iMac10,1-21.5-inch",
        "iMac10,1-27-inch",
        "iMac11,1",
        "iMac11,2",
        "iMac11,3",
        "iMac12,1-Late-2011",
        "iMac12,1-Mid-2011",
        "iMac12,2",
        "iMac13,1",
        "iMac13,2",
        "iMac13,3",
        "MacBook5,1",
        "MacBook5,2-Early-2009",
        "MacBook5,2-Mid-2009",
        "MacBook6,1",
        "MacBook7,1",
        "MacBookAir2,1-2008",
        "MacBookAir2,1-2009",
        "MacBookAir3,1",
        "MacBookAir3,2",
        "MacBookAir4,1",
        "MacBookAir4,2",
        "MacBookAir5,1",
        "MacBookAir5,2",
        "MacBookPro3,1-15-inch-Late-2007",
        "MacBookPro3,1-15-inch-Mid-2007",
        "MacBookPro3,1-17-inch-Late-2007",
        "MacBookPro3,1-17-inch-Mid-2007",
        "MacBookPro4,1-15-inch",
        "MacBookPro4,1-17-inch",
        "MacBookPro5,1-2008",
        "MacBookPro5,1-2009",
        "MacBookPro5,2-Early-2009",
        "MacBookPro5,2-Mid-2009",
        "MacBookPro5,3",
        "MacBookPro5,4",
        "MacBookPro5,5",
        "MacBookPro6,1",
        "MacBookPro6,2",
        "MacBookPro7,1",
        "MacBookPro8,1-Early-2011",
        "MacBookPro8,1-Late-2011",
        "MacBookPro8,2-Early-2011",
        "MacBookPro8,2-Late-2011",
        "MacBookPro8,3-Early-2011",
        "MacBookPro8,3-Late-2011",
        "MacBookPro9,1",
        "MacBookPro9,2",
        "MacBookPro10,1-Early-2013",
        "MacBookPro10,1-Mid-2012",
        "MacBookPro10,2-Early-2013",
        "MacBookPro10,2-Late-2012",
        "Macmini3,1-Early-2009",
        "Macmini3,1-Late-2009",
        "Macmini4,1",
        "Macmini5,1",
        "Macmini5,2",
        "Macmini5,3",
        "Macmini6,1",
        "Macmini6,2",
        "MacPro3,1",
        "MacPro4,1",
        "MacPro5,1-2010",
        "MacPro5,1-2012",
        "MacPro5,1-Server-2010",
        "MacPro5,1-Server-2012",
        "Xserve3,1"
    ],
    "sources": [
        {
            "type": "update",
            "deviceMap": [
                "iMac7,1-20-inch",
                "iMac7,1-24-inch",
                "iMac8,1-20-inch",
                "iMac8,1-24-inch",
                "iMac9,1-20-inch-Early-2009",
                "iMac9,1-20-inch-Mid-2009",
                "iMac9,1-24-inch",
                "iMac10,1-21.5-inch",
                "iMac10,1-27-inch",
                "iMac11,1",
                "iMac11,2",
                "iMac11,3",
                "iMac12,1-Late-2011",
                "iMac12,1-Mid-2011",
                "iMac12,2",
                "iMac13,1",
                "iMac13,2",
                "iMac13,3",
                "MacBook5,1",
                "MacBook5,2-Early-2009",
                "MacBook5,2-Mid-2009",
                "MacBook6,1",
                "MacBook7,1",
                "MacBookAir2,1-2008",
                "MacBookAir2,1-2009",
                "MacBookAir3,1",
                "MacBookAir3,2",
                "MacBookAir4,1",
                "MacBookAir4,2",
                "MacBookAir5,1",
                "MacBookAir5,2",
                "MacBookPro3,1-15-inch-Late-2007",
                "MacBookPro3,1-15-inch-Mid-2007",
                "MacBookPro3,1-17-inch-Late-2007",
                "MacBookPro3,1-17-inch-Mid-2007",
                "MacBookPro4,1-15-inch",
                "MacBookPro4,1-17-inch",
                "MacBookPro5,1-2008",
                "MacBookPro5,1-2009",
                "MacBookPro5,2-Early-2009",
                "MacBookPro5,2-Mid-2009",
                "MacBookPro5,3",
                "MacBookPro5,4",
                "MacBookPro5,5",
                "MacBookPro6,1",
                "MacBookPro6,2",
                "MacBookPro7,1",
                "MacBookPro8,1-Early-2011",
                "MacBookPro8,1-Late-2011",
                "MacBookPro8,2-Early-2011",
                "MacBookPro8,2-Late-2011",
                "MacBookPro8,3-Early-2011",
                "MacBookPro8,3-Late-2011",
                "MacBookPro9,1",
                "MacBookPro9,2",
                "MacBookPro10,1-Early-2013",
                "MacBookPro10,1-Mid-2012",
                "MacBookPro10,2-Early-2013",
                "MacBookPro10,2-Late-2012",
                "Macmini3,1-Early-2009",
                "Macmini3,1-Late-2009",
                "Macmini4,1",
                "Macmini5,1",
                "Macmini5,2",
                "Macmini5,3",
                "Macmini6,1",
                "Macmini6,2",
                "MacPro3,1",
                "MacPro4,1",
                "MacPro5,1-2010",
                "MacPro5,1-2012",
                "MacPro5,1-Server-2010",
                "MacPro5,1-Server-2012",
                "Xserve3,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2019/cert/041-88062-20191011-f57464ba-0b7b-4afc-8057-17cc54b10d86/SecUpd2013-003.dmg",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "671557b5f9ccdea2ebe5ff49c3beaf16"
            },
            "size": 20383112
        }
    ]
}

=== littlebyteorg/appledb/osFiles/bridgeOS/19x - 6.x/19P4243.json
{
    "osStr": "bridgeOS",
    "version": "6.4",
    "build": "19P4243",
    "restoreVersion": "19.16.14243.0.0,0",
    "buildId": "253CEFC8-A697-11EC-9EC6-EA009B2E3A12",
    "buildTrain": "StarBridgeE",
    "released": "2022-03-31",
    "deviceMap": [
        "iBridge2,1",
        "iBridge2,3",
        "iBridge2,4",
        "iBridge2,5",
        "iBridge2,6",
        "iBridge2,7",
        "iBridge2,8",
        "iBridge2,10",
        "iBridge2,12",
        "iBridge2,14",
        "iBridge2,15",
        "iBridge2,16",
        "iBridge2,19",
        "iBridge2,20",
        "iBridge2,21",
        "iBridge2,22"
    ],
    "sources": [
        {
            "type": "ipsw",
            "systemImageId": "27BF9417-D1FD-4A9D-A830-1C870B1BAB9F",
            "deviceMap": [
                "iBridge2,1",
                "iBridge2,3",
                "iBridge2,4",
                "iBridge2,5",
                "iBridge2,6",
                "iBridge2,7",
                "iBridge2,8",
                "iBridge2,10",
                "iBridge2,12",
                "iBridge2,14",
                "iBridge2,15",
                "iBridge2,16",
                "iBridge2,19",
                "iBridge2,20",
                "iBridge2,21",
                "iBridge2,22"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2022SpringFCS/fullrestores/002-82670/A85D86CB-3DB5-4159-8F58-EA9D589F4849/iBridge2,1,iBridge2,10,iBridge2,12,iBridge2,14,iBridge2,15,iBridge2,16,iBridge2,19,iBridge2,20,iBridge2,21,iBridge2,22,iBridge2,3,iBridge2,4,iBridge2,5,iBridge2,6,iBridge2,7,iBridge2,8_6.4_19P4243_Restore.ipsw",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "70db1c9154851619c1a8012e87e0238a",
                "sha1": "09f169e65d8f7650d10bdff3501354f06efe2b9e",
                "sha2-256": "6d8ed4c65db87febe6ff9146e16b886124fbaadb8833d753140d82cf447d4a7c"
            },
            "size": 629550682
        },
        {
            "type": "pkg",
            "deviceMap": [
                "iBridge2,1",
                "iBridge2,3",
                "iBridge2,4",
                "iBridge2,5",
                "iBridge2,6",
                "iBridge2,7",
                "iBridge2,8",
                "iBridge2,10",
                "iBridge2,12",
                "iBridge2,14",
                "iBridge2,15",
                "iBridge2,16",
                "iBridge2,19",
                "iBridge2,20",
                "iBridge2,21",
                "iBridge2,22"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/52/32/002-79221-A_ODVCIPEQ8Z/pm6npz56lk7dckhfz7ejmnok8mok2ianug/BridgeOSUpdateCustomer.pkg",
                    "active": false
                }
            ],
            "size": 490890302
        }
    ]
}

=== littlebyteorg/appledb/osFiles/bridgeOS/16x - 3.x/16P52540a.json
{
    "osStr": "bridgeOS",
    "version": "3.2 beta 3",
    "build": "16P52540a",
    "restoreVersion": "16.16.2540.5.1,0",
    "buildId": "7837AFD4-E709-11E8-9FAF-E0B07D830EEE",
    "buildTrain": "bridgeOSLibertyCSeed",
    "released": "2018-11-15",
    "beta": true,
    "deviceMap": [
        "iBridge2,1",
        "iBridge2,3",
        "iBridge2,4",
        "iBridge2,5",
        "iBridge2,7",
        "iBridge2,8"
    ],
    "sources": [
        {
            "type": "pkg",
            "systemImageId": "8947FB3E-7421-4BE2-BD0C-5F251FC14E5E",
            "deviceMap": [
                "iBridge2,1",
                "iBridge2,3",
                "iBridge2,4",
                "iBridge2,5",
                "iBridge2,7",
                "iBridge2,8"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/17/29/041-24617/hdodx9ze4j4gkxsozxdtmd5ppeuivguuy3/BridgeOSUpdateCustomer.pkg",
                    "active": false
                }
            ],
            "size": 323947813
        },
        {
            "type": "pkg",
            "deviceMap": [
                "iBridge2,1",
                "iBridge2,3",
                "iBridge2,4",
                "iBridge2,5",
                "iBridge2,7",
                "iBridge2,8"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/22/41/041-25636/mw0ttqc350yaoi4tll06518l6jymicvbt0/BridgeOSUpdateCustomer.pkg",
                    "active": false
                }
            ],
            "size": 323947821
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Apple Devices/1.1030.20993.0.json
{
    "osStr": "Apple Devices",
    "version": "1.1030.20993.0",
    "released": "2024-03-28",
    "deviceMap": [
        "Apple Devices"
    ],
    "sources": [
        {
            "type": "appx",
            "deviceMap": [
                "Apple Devices"
            ],
            "windowsUpdateDetails": {
                "updateId": "6a1ef620-5590-425e-9b33-e8945f9ecf4e",
                "revisionId": "1"
            },
            "links": [
                {
                    "url": "https://apps.microsoft.com/store/detail/9NP83LWLPZ9K",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "b165191dd5e337259e77b162b27ebeed86d8f9a4",
                "sha2-256": "eaa44b7cca00647bd54f04a9e928941956d3efedbeba02f82590b3fbfc738011"
            },
            "size": 224001769
        }
    ]
}

=== littlebyteorg/appledb/osFiles/bridgeOS/18x/18P52551s.json
{
    "osStr": "bridgeOS",
    "version": "5.0.1 beta",
    "build": "18P52551s",
    "released": "2020-10-28",
    "beta": true,
    "deviceMap": [
        "iBridge2,1",
        "iBridge2,3",
        "iBridge2,4",
        "iBridge2,5",
        "iBridge2,6",
        "iBridge2,7",
        "iBridge2,8",
        "iBridge2,10",
        "iBridge2,12",
        "iBridge2,14",
        "iBridge2,15",
        "iBridge2,16",
        "iBridge2,19",
        "iBridge2,20",
        "iBridge2,21",
        "iBridge2,22"
    ],
    "sources": [
        {
            "type": "pkg",
            "deviceMap": [
                "iBridge2,1",
                "iBridge2,3",
                "iBridge2,4",
                "iBridge2,5",
                "iBridge2,6",
                "iBridge2,7",
                "iBridge2,8",
                "iBridge2,10",
                "iBridge2,12",
                "iBridge2,14",
                "iBridge2,15",
                "iBridge2,16",
                "iBridge2,19",
                "iBridge2,20",
                "iBridge2,21",
                "iBridge2,22"
            ],
            "links": [
                {
                    "url": "http://swcdn.apple.com/content/downloads/16/13/001-58877-A_39XMCAVLFG/0dygc5fjj52xaox8r7c6n6niup2fe24a3y/BridgeOSUpdateCustomer.pkg",
                    "active": false
                }
            ],
            "size": 441765045
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Safari/4.x/4.0.2.json
{
    "osStr": "Safari",
    "version": "4.0.2",
    "released": "2009-07-08",
    "securityNotes": "https://support.apple.com/HT3666",
    "deviceMap": [
        "Safari (Windows)",
        "Safari (macOS)"
    ],
    "osMap": [
        "Mac OS X 10.4",
        "Mac OS X 10.5",
        "Windows XP",
        "Windows Vista",
        "Windows 7"
    ],
    "sources": [
        {
            "type": "exe",
            "deviceMap": [
                "Safari (Windows)"
            ],
            "osMap": [
                "Windows XP",
                "Windows Vista",
                "Windows 7"
            ],
            "links": [
                {
                    "url": "http://appldnld.apple.com/Safari4/061-6759.20090708.Lki98/SafariSetup.exe",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "2e74dc2c47d414f9f34d845965d7f6da"
            },
            "size": 28464416
        },
        {
            "type": "dmg",
            "deviceMap": [
                "Safari (macOS)"
            ],
            "osMap": [
                "Mac OS X 10.5"
            ],
            "links": [
                {
                    "url": "http://appldnld.apple.com/Safari4/061-6761.20090708.AsxpI/Safari4.0.2Leo.dmg",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "93d5a350d96bb0949039d35b415c0ccb"
            },
            "size": 41908858
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/QuickTime/7.x/7.6.8.json
{
    "osStr": "QuickTime",
    "version": "7.6.8",
    "released": "2010-09-15",
    "securityNotes": "http://support.apple.com/kb/HT4339",
    "deviceMap": [
        "QuickTime (Windows)"
    ],
    "osMap": [
        "Windows XP SP2",
        "Windows Vista",
        "Windows 7"
    ],
    "sources": [
        {
            "type": "exe",
            "deviceMap": [
                "QuickTime (Windows)"
            ],
            "osMap": [
                "Windows XP SP2",
                "Windows Vista",
                "Windows 7"
            ],
            "links": [
                {
                    "url": "http://appldnld.apple.com/QuickTime/061-8938.20100915.Qts3T/QuickTimeInstaller.exe",
                    "active": true
                }
            ]
        }
    ]
}
