=== littlebyteorg/appledb/schemas/osFiles.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Apple OS",
    "description": "Description of an Apple operating system release",
    "$ref": "#/definitions/os",
    "type": "object",
    "required": ["osStr", "version"],
    "definitions": {
        "os": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "osStr":         {"type": "string"},
                "version":       {"type": "string", "not": { "pattern": "FIXME" }},
                "iosVersion":    {"type": "string"},
                "safariVersion": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "build":         {"type": "string"},
                "restoreVersion": {"type": "string"},
                "buildId":       {"type": "string", "format": "uuid"},
                "uniqueBuild":   {"type": "string"},
                "key":           {"type": "string"},
                
                "bridgeOSBuild":    {"type": "string"},
                "embeddedOSBuild":  {"type": "string"},
                "basebandVersions": {
                    "type":"object",
                    "additionalProperties": true
                },
                "buildTrain":    {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },

                "released":     {"anyOf": [
                    {"type": "string", "format": "date-time"},
                    {"type": "string", "format": "date"},
                    {"type": "string", "pattern": "^\\d{4}-\\d{2}$"},
                    {"type": "string", "pattern": "^\\d{4}$"},
                    {"type": "string", "maxLength": 0}
                ]},
                "rc":           {"type": "boolean"},
                "beta":         {"type": "boolean"},
                "rsr":          {"type": "boolean"},
                "internal":     {"type": "boolean"},
                "hideFromLatestVersions": {"type": "boolean"},
                "notes":        {"type": "string"},
                "releaseNotes": {
                    "anyOf": [
                        {"type": "string", "format": "uri"},
                        {"$ref": "#/definitions/sourceLink"}
                    ]
                },
                "securityNotes": {
                    "anyOf": [
                        {"type": "string", "format": "uri"},
                        {"$ref": "#/definitions/sourceLink"}
                    ]
                },

                "preinstalled": {
                    "anyOf": [
                        {"type": "boolean"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "deviceMap": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "uniqueItems": true
                },
                "osMap": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "uniqueItems": true
                },
                "ipd": {
                    "type": "object",
                    "properties": {
                        "AudioAccessory": {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "AppleTV":  {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPhone":   {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPad":     {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPod":     {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        }
                    },
                    "additionalProperties": {
                        "anyOf": [
                            {"type": "string", "format": "uri"},
                            {"$ref": "#/definitions/sourceLink"}
                        ]
                    }
                },
                "createDuplicateEntries": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "allOf": [
                            {"$ref": "#/definitions/os"},
                            {"type": "object", "properties": {"createDuplicateEntries": false}}
                        ]
                    }
                },
                "sdks": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "beta": {"type": "boolean"},
                            "build": {"type": "string"},
                            "osStr": {"type": "string"},
                            "rc": {"type": "boolean"},
                            "version": {"type": "string"}
                        }
                    }
                },
                "appledbWebImage": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "id": {"type": "string"},
                        "align": {"type": "string"}
                    }
                },
                "appledbUrl": {"type": "string"},
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["type", "links", "deviceMap"],
                        "properties": {
                            "type": {"enum": ["ipsw", "ota", "update", "kdk", "installassistant", "combo", "pkg", "aar", "dmg", "exe", "appx", "apk", "xip", "tar", "bin", "ipa", "xpi"]},
                            "deviceMap": {"$ref": "#/definitions/os/properties/deviceMap"},
                            "boardMap": {
                                "type": "array",
                                "minItems": 1,
                                "items": {"type": "string"},
                                "uniqueItems": true
                            },
                            "osMap": {"$ref": "#/definitions/os/properties/osMap"},
                            "skipUpdateLinks": {"type": "boolean"},
                            "windowsUpdateDetails": {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "updateId": {"type": "string", "format": "uuid"},
                                    "revisionId": {"type": "string", "pattern": "^\\w+$"}
                                }
                            },
                            "hashes": {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "md5":      { "type": "string", "pattern": "^[0-9a-f]{32}$" },
                                    "sha1":     { "type": "string", "pattern": "^[0-9a-f]{40}$" },
                                    "sha2-256": { "type": "string", "pattern": "^[0-9a-f]{64}$" },
                                    "sha2-512": { "type": "string", "pattern": "^[0-9a-f]{128}$" }
                                }
                            },
                            "links": {
                                "type": "array",
                                "minItems": 1,
                                "items": {
                                    "$ref": "#/definitions/sourceLink"
                                }
                            },
                            "prerequisiteBuild": {
                                "anyOf": [
                                    {"type": "string"},
                                    {"type": "array", "minItems": 1, "items": {"type": "string"}}
                                ]
                            },
                            "systemImageId": {"type": "string", "format": "uuid"},
                            "size": {"type": "integer"}
                        }
                    }
                }
            }
        },
        "sourceLink": {
            "type": "object",
            "additionalProperties": false,
            "required": ["url", "active"],
            "properties": {
                "url": {"type": "string", "format": "uri"},
                "decryptionKey": {"type": "string"},
                "active": {"type": "boolean"},
                "catalog": {"enum": ["dev-beta", "public-beta"]}
            }
        }
    }
}

=== littlebyteorg/appledb/osFiles/Software/Safari Technology Preview/36.json
{
    "osStr": "Safari Technology Preview",
    "version": "36",
    "safariVersion": "11.0",
    "released": "2017-07-26",
    "beta": true,
    "releaseNotes": "https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-36",
    "deviceMap": [
        "Safari Technology Preview"
    ],
    "osMap": [
        "macOS 10.12",
        "macOS 10.13"
    ],
    "sources": [
        {
            "type": "dmg",
            "deviceMap": [
                "Safari Technology Preview"
            ],
            "osMap": [
                "macOS 10.12"
            ],
            "links": [
                {
                    "url": "https://secure-appldnld.apple.com/STP/091-23520-20170726-AC590232-714D-11E7-958D-19D4484DD6D5/SafariTechnologyPreview.dmg",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "19a04bdfb18e4cde87022bec0825797c",
                "sha1": "0db7654283aaf59027731d0104e03923e6ada388",
                "sha2-256": "cc3aae7d80ede050c50addc73cbbc7bab8a4a95787fb8bf29c73aa801f1d771d"
            },
            "size": 68984219
        },
        {
            "type": "dmg",
            "deviceMap": [
                "Safari Technology Preview"
            ],
            "osMap": [
                "macOS 10.13"
            ],
            "links": [
                {
                    "url": "https://secure-appldnld.apple.com/STP/091-23518-20170726-AC590278-714D-11E7-958D-1AD4484DD6D5/SafariTechnologyPreview.dmg",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "80d2e4abb9f4ce6c02444719f8c71c63",
                "sha1": "dbd1cae77c80752ba546bc921e0bfe00dbeed78f",
                "sha2-256": "9db2bb7740614d37f27c828f8bbd818e07d49de33fe79cbc4c0a68b96c7945b5"
            },
            "size": 68873635
        }
    ]
}

=== littlebyteorg/appledb/osFiles/macOS/14x - 10.10.x/14D2134.json
{
    "osStr": "OS X",
    "version": "10.10.3",
    "build": "14D2134",
    "buildTrain": "SUSyrahDomeHW",
    "released": "2015-04-16",
    "preinstalled": true,
    "appledbWebImage": {
        "id": "Yosemite",
        "align": "left"
    },
    "deviceMap": [
        "MacBookPro11,4",
        "MacBookPro11,5"
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Safari/16.x/614D19.json
{
    "osStr": "Safari",
    "version": "16.3 beta 3",
    "build": "614D19",
    "released": "2023-01-18",
    "beta": true,
    "deviceMap": [
        "Safari (macOS)"
    ],
    "osMap": [
        "macOS 11"
    ],
    "sources": [
        {
            "type": "pkg",
            "deviceMap": [
                "Safari (macOS)"
            ],
            "osMap": [
                "macOS 11"
            ],
            "links": [
                {
                    "url": "http://swcdn.apple.com/content/downloads/49/20/032-35628-A_8UVCSDLEYN/dd389xfepd6uutlenj6gdsglhmm1c618ff/Safari16.3BigSurAutoSeed.pkg",
                    "active": false
                }
            ],
            "size": 128502643
        }
    ]
}

=== littlebyteorg/appledb/osFiles/tvOS/13x - 9.x/13Y5752a.json
{
    "osStr": "tvOS",
    "version": "9.2.1 beta",
    "build": "13Y5752a",
    "buildTrain": "FernSeed",
    "released": "2016-04-06",
    "beta": true,
    "deviceMap": [
        "AppleTV5,3"
    ],
    "sources": [
        {
            "type": "ipsw",
            "deviceMap": [
                "AppleTV5,3"
            ],
            "links": [
                {
                    "url": "https://developer.apple.com/services-account/download?path=/iOS/tvOS_9.2.1_beta_Restore_Image/AppleTV53_9.2.1_13Y5752a_Restore.ipsw",
                    "active": false
                }
            ],
            "size": 1145053486
        },
        {
            "type": "ota",
            "deviceMap": [
                "AppleTV5,3"
            ],
            "links": [
                {
                    "url": "http://appldnld.apple.com/tvosseeds/031-56520-20160406-7D09A73C-FAC2-11E5-BD98-BAE2016A2A1A/com_apple_MobileAsset_SoftwareUpdate/1e9069bef79ee17ad74f5ec3836b1a5914f63413.zip",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "5b9728c163d71d73d78bb717878a1e93"
            },
            "size": 855495243
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Safari/26.x/622A69.json
{
    "osStr": "Safari",
    "version": "26.0 beta 6",
    "build": "622A69",
    "buildTrain": "SafariCheerSequoia",
    "released": "2025-09-02",
    "beta": true,
    "releaseNotes": {
        "url": "https://developer.apple.com/services-account/download?path=/Safari/Safari_26.0_for_macOS_Sonoma_and_Safari_26.0_for_macOS_Sequoia_beta_6/Safari_26.0_Beta_6_Notes.pdf",
        "active": false
    },
    "deviceMap": [
        "Safari (macOS)"
    ],
    "osMap": [
        "macOS 15"
    ],
    "sources": [
        {
            "type": "dmg",
            "deviceMap": [
                "Safari (macOS)"
            ],
            "osMap": [
                "macOS 15"
            ],
            "links": [
                {
                    "url": "https://developer.apple.com/services-account/download?path=/Safari/Safari_26.0_for_macOS_Sonoma_and_Safari_26.0_for_macOS_Sequoia_beta_6/Safari_26.0_for_macOS_Sequoia_beta_6.dmg",
                    "active": false
                }
            ],
            "size": 225401695
        },
        {
            "type": "pkg",
            "deviceMap": [
                "Safari (macOS)"
            ],
            "osMap": [
                "macOS 15"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/52/20/093-30896-A_YEJI61SEPT/a9h2hjf8ynvcapy4qkxg1hdanmdlf25w28/Safari26.0SequoiaAutoSeed.pkg",
                    "active": false
                }
            ],
            "hashes": {
                "md5": "dc3861ac4d9ca48563f5a92d1cb0d58d",
                "sha1": "586b5f0d612853cd9bf32fa40b514d259ff2b32a",
                "sha2-256": "3c2be3a1db07166c9251ed8ca17cbb5348d105f85dbf2e71dbaf20897d58d808"
            },
            "size": 225710640
        }
    ]
}

=== littlebyteorg/appledb/osFiles/bridgeOS/18x - 5.x/18P54646b.json
{
    "osStr": "bridgeOS",
    "version": "5.4 beta",
    "build": "18P54646b",
    "restoreVersion": "18.16.14646.5.2,0",
    "buildId": "58E627E2-9C14-11EB-AD5D-BF571F136069",
    "buildTrain": "GoldenGateBridgeFSeed",
    "released": "2021-04-21",
    "beta": true,
    "deviceMap": [
        "iBridge2,1",
        "iBridge2,3",
        "iBridge2,4",
        "iBridge2,5",
        "iBridge2,6",
        "iBridge2,7",
        "iBridge2,8",
        "iBridge2,10",
        "iBridge2,12",
        "iBridge2,14",
        "iBridge2,15",
        "iBridge2,16",
        "iBridge2,19",
        "iBridge2,20",
        "iBridge2,21",
        "iBridge2,22"
    ],
    "sources": [
        {
            "type": "pkg",
            "systemImageId": "59157BF2-329E-4BFB-B6AA-AEA54CE19FB2",
            "deviceMap": [
                "iBridge2,1",
                "iBridge2,3",
                "iBridge2,4",
                "iBridge2,5",
                "iBridge2,6",
                "iBridge2,7",
                "iBridge2,8",
                "iBridge2,10",
                "iBridge2,12",
                "iBridge2,14",
                "iBridge2,15",
                "iBridge2,16",
                "iBridge2,19",
                "iBridge2,20",
                "iBridge2,21",
                "iBridge2,22"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/60/26/071-29401-A_BTAO0AKEJ3/8e68jv2nbeljac66e9r8r9oe3s60dddy30/BridgeOSUpdateCustomer.pkg",
                    "active": false
                }
            ],
            "size": 464929377
        }
    ]
}

=== littlebyteorg/appledb/osFiles/visionOS/21x - 1.x/21O5761a.json
{
    "osStr": "visionOS",
    "version": "1.3 beta 3",
    "build": "21O5761a",
    "restoreVersion": "21.15.761.5.1,0",
    "buildTrain": "BorealisGSeed",
    "released": "2024-07-09",
    "beta": true,
    "deviceMap": [
        "RealityDevice14,1"
    ],
    "sources": [
        {
            "type": "ipsw",
            "deviceMap": [
                "RealityDevice14,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2024SpringSeed/fullrestores/062-28277/9AF374CC-6D65-4B59-9C60-FD69691D4AB6/Apple_Vision_Pro_1.3_21O5761a_Restore.ipsw",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "fd0f41beddef3f1369066405cd201ff0e166c6b8",
                "sha2-256": "02480bb499944763bc11dccdeaae51d7e04b14568b35c1ecf50a855b1641d053"
            },
            "size": 9187698657
        },
        {
            "type": "ota",
            "deviceMap": [
                "RealityDevice14,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2024SpringSeed/patches/062-28281/AF732DE9-E2AE-4A34-A367-C948D47B677B/com_apple_MobileAsset_SoftwareUpdate/2f1c6a740965c75b5bec8f3ef98cb2d2782c5942.zip",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "8332c783eb70c459efde261577a7f056972ea9a8",
                "sha2-256": "4b80a675c71d0048bd7425f57491a35fef3fd2009614378d2bdb7b9c40f96c73"
            },
            "size": 7538272937
        },
        {
            "type": "ota",
            "prerequisiteBuild": "21O5587a",
            "deviceMap": [
                "RealityDevice14,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2024SpringSeed/patches/062-28279/17D4A1DD-DCB6-4B71-83E3-50136BCEBBF8/com_apple_MobileAsset_SoftwareUpdate/2e25726f98a2359f81c58efc7b637d3c2c93a96b.zip",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "20877e7b945ae7a2dbeb1696130c20d2070250ab",
                "sha2-256": "e0baa9d3c598a70344a00071beb25344e95eb2a191d7cb9fabfae61cf5ce63ac"
            },
            "size": 1414257788
        },
        {
            "type": "ota",
            "prerequisiteBuild": "21O5756a",
            "deviceMap": [
                "RealityDevice14,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2024SpringSeed/patches/062-28734/DB8017DD-826A-4EC2-B29D-A49C0CD8DA6B/com_apple_MobileAsset_SoftwareUpdate/21a964ca852941ebc7c54a6f225f4bf166d110d8.zip",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "e7d3f116913bd90a67af3fe13583cd3b3268c6bc",
                "sha2-256": "6e29c1bc6a94bdf091553ed70e4443800b9496d792df236c8ed390745a35f14c"
            },
            "size": 668616020
        }
    ]
}

=== littlebyteorg/appledb/osFiles/watchOS/18x - 7.x/18R5327h.json
{
    "osStr": "watchOS",
    "version": "7.0 beta 2",
    "build": "18R5327h",
    "buildTrain": "HunterSeed",
    "released": "2020-07-07",
    "beta": true,
    "deviceMap": [
        "Watch3,1",
        "Watch3,2",
        "Watch3,3",
        "Watch3,4",
        "Watch4,1",
        "Watch4,2",
        "Watch4,3",
        "Watch4,4",
        "Watch5,1",
        "Watch5,2",
        "Watch5,3",
        "Watch5,4"
    ],
    "basebandVersions": {
        "Watch3,1": "4.70.00",
        "Watch3,2": "4.70.00",
        "Watch4,3": "2.50.27",
        "Watch4,4": "2.50.27",
        "Watch5,3": "2.50.27",
        "Watch5,4": "2.50.27"
    },
    "sources": [
        {
            "type": "ota",
            "deviceMap": [
                "Watch3,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-24045/F361B45B-FD64-4097-A872-36C0D2B14E81/com_apple_MobileAsset_SoftwareUpdate/67d1894737fe6d46afe563403f7768d1740278e9.zip",
                    "active": true
                }
            ],
            "size": 1708729845
        },
        {
            "type": "ota",
            "deviceMap": [
                "Watch3,2"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-24060/BDDF4E81-F802-4F21-A44F-47DE8A817637/com_apple_MobileAsset_SoftwareUpdate/a9aedc8196bb19d44a58594551e09df4e1d09e3c.zip",
                    "active": true
                }
            ],
            "size": 1717079608
        },
        {
            "type": "ota",
            "prerequisiteBuild": "17U5559d",
            "deviceMap": [
                "Watch3,2"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-23889/99864B9C-056F-4699-989E-E361E7BD370A/com_apple_MobileAsset_SoftwareUpdate/fb3e31aafb5e2eb7fdc9f657901d83e42a699ef1.zip",
                    "active": true
                }
            ],
            "size": 1049974724
        },
        {
            "type": "ota",
            "deviceMap": [
                "Watch3,3"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-23867/BAF6E711-F365-466E-A69A-1C37081BDB65/com_apple_MobileAsset_SoftwareUpdate/799a09ae14a1029b777f3d9cf7b3180636a643f3.zip",
                    "active": true
                }
            ],
            "size": 1641953382
        },
        {
            "type": "ota",
            "deviceMap": [
                "Watch3,4"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-23832/ED07B7A9-3D61-4F98-9572-5BC22455DDEC/com_apple_MobileAsset_SoftwareUpdate/0e2b6f93d206e9ee16863e0fd1a12aa33fbaf763.zip",
                    "active": true
                }
            ],
            "size": 1652071096
        },
        {
            "type": "ota",
            "deviceMap": [
                "Watch4,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-23981/A1BADA43-9F64-4833-9084-C45D0FDFF5CB/com_apple_MobileAsset_SoftwareUpdate/e2efe7bfbee4817339f35455f38eb00a9f0a57fd.zip",
                    "active": true
                }
            ],
            "size": 1701581101
        },
        {
            "type": "ota",
            "deviceMap": [
                "Watch4,2"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-23959/28397362-69DA-494D-962D-D88CBE9B90AE/com_apple_MobileAsset_SoftwareUpdate/82213486cabbd9eb237ecc01f6c76344563d5ae9.zip",
                    "active": true
                }
            ],
            "size": 1674681191
        },
        {
            "type": "ota",
            "prerequisiteBuild": "16U674",
            "deviceMap": [
                "Watch4,2"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-23850/17616031-4D67-43CD-AA58-CF0D6FB1B38C/com_apple_MobileAsset_SoftwareUpdate/d6121007162a753ddcdac386f1b7a05a53bb182d.zip",
                    "active": true
                }
            ],
            "size": 1204844772
        },
        {
            "type": "ota",
            "deviceMap": [
                "Watch4,3"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-23976/F8DC3679-DC84-4A70-AE29-6A686651B545/com_apple_MobileAsset_SoftwareUpdate/96cee88134245ffb7fe14daf033bcd4550103885.zip",
                    "active": true
                }
            ],
            "size": 1745812693
        },
        {
            "type": "ota",
            "deviceMap": [
                "Watch4,4"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-24020/904DC35A-A75C-4B5D-9786-EA1061C37A12/com_apple_MobileAsset_SoftwareUpdate/d5198188b3b93f185df18763a05c9d546e38cb2d.zip",
                    "active": true
                }
            ],
            "size": 1716987940
        },
        {
            "type": "ota",
            "deviceMap": [
                "Watch5,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-24051/EC80AAE2-FE60-4C63-9D6A-A9CD3F57A55B/com_apple_MobileAsset_SoftwareUpdate/320973dee73c16eb6f1495a3b3694c9546ac8b38.zip",
                    "active": true
                }
            ],
            "size": 1702667930
        },
        {
            "type": "ota",
            "deviceMap": [
                "Watch5,2"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-23977/3E06FD35-2F77-4F35-A963-2F9559CC0AC0/com_apple_MobileAsset_SoftwareUpdate/e4284487b3bc5dc27168ed49d697df4979aece43.zip",
                    "active": true
                }
            ],
            "size": 1676473493
        },
        {
            "type": "ota",
            "deviceMap": [
                "Watch5,3"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-23938/838736BC-D6B5-4522-B28B-F114049F878D/com_apple_MobileAsset_SoftwareUpdate/a3004fd2e4f08f839ea71e2010f23009a877c2d8.zip",
                    "active": true
                }
            ],
            "size": 1746947715
        },
        {
            "type": "ota",
            "deviceMap": [
                "Watch5,4"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2020SummerSeed/patches/001-23945/C68DC658-565B-449D-BBB3-5E73209936E4/com_apple_MobileAsset_SoftwareUpdate/1d9048e5f8180dc17ee28af753a99c8427106b43.zip",
                    "active": true
                }
            ],
            "size": 1718223733
        }
    ]
}
